// Generated by gencpp from file naoqi_bridge_msgs/BlinkResult.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_BLINKRESULT_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_BLINKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct BlinkResult_
{
  typedef BlinkResult_<ContainerAllocator> Type;

  BlinkResult_()
    : still_blinking(false)  {
    }
  BlinkResult_(const ContainerAllocator& _alloc)
    : still_blinking(false)  {
  (void)_alloc;
    }



   typedef uint8_t _still_blinking_type;
  _still_blinking_type still_blinking;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> const> ConstPtr;

}; // struct BlinkResult_

typedef ::naoqi_bridge_msgs::BlinkResult_<std::allocator<void> > BlinkResult;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::BlinkResult > BlinkResultPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::BlinkResult const> BlinkResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator2> & rhs)
{
  return lhs.still_blinking == rhs.still_blinking;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53e041b81450f9247036f13b3c0bf822";
  }

  static const char* value(const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53e041b81450f924ULL;
  static const uint64_t static_value2 = 0x7036f13b3c0bf822ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/BlinkResult";
  }

  static const char* value(const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool still_blinking\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.still_blinking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlinkResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::BlinkResult_<ContainerAllocator>& v)
  {
    s << indent << "still_blinking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.still_blinking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_BLINKRESULT_H
