// Generated by gencpp from file naoqi_bridge_msgs/CmdPoseService.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_CMDPOSESERVICE_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_CMDPOSESERVICE_H

#include <ros/service_traits.h>


#include <naoqi_bridge_msgs/CmdPoseServiceRequest.h>
#include <naoqi_bridge_msgs/CmdPoseServiceResponse.h>


namespace naoqi_bridge_msgs
{

struct CmdPoseService
{

typedef CmdPoseServiceRequest Request;
typedef CmdPoseServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CmdPoseService
} // namespace naoqi_bridge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_bridge_msgs::CmdPoseService > {
  static const char* value()
  {
    return "271cb12677c4cd9bccbc642cd9258d1f";
  }

  static const char* value(const ::naoqi_bridge_msgs::CmdPoseService&) { return value(); }
};

template<>
struct DataType< ::naoqi_bridge_msgs::CmdPoseService > {
  static const char* value()
  {
    return "naoqi_bridge_msgs/CmdPoseService";
  }

  static const char* value(const ::naoqi_bridge_msgs::CmdPoseService&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_bridge_msgs::CmdPoseServiceRequest> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::CmdPoseService >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::CmdPoseServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::CmdPoseService >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::CmdPoseServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::CmdPoseServiceRequest> should match
// service_traits::DataType< ::naoqi_bridge_msgs::CmdPoseService >
template<>
struct DataType< ::naoqi_bridge_msgs::CmdPoseServiceRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::CmdPoseService >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::CmdPoseServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_bridge_msgs::CmdPoseServiceResponse> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::CmdPoseService >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::CmdPoseServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::CmdPoseService >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::CmdPoseServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::CmdPoseServiceResponse> should match
// service_traits::DataType< ::naoqi_bridge_msgs::CmdPoseService >
template<>
struct DataType< ::naoqi_bridge_msgs::CmdPoseServiceResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::CmdPoseService >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::CmdPoseServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_CMDPOSESERVICE_H
