// Generated by gencpp from file naoqi_bridge_msgs/FadeRGB.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_FADERGB_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_FADERGB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct FadeRGB_
{
  typedef FadeRGB_<ContainerAllocator> Type;

  FadeRGB_()
    : led_name()
    , color()
    , fade_duration()  {
    }
  FadeRGB_(const ContainerAllocator& _alloc)
    : led_name(_alloc)
    , color(_alloc)
    , fade_duration()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _led_name_type;
  _led_name_type led_name;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef ros::Duration _fade_duration_type;
  _fade_duration_type fade_duration;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> const> ConstPtr;

}; // struct FadeRGB_

typedef ::naoqi_bridge_msgs::FadeRGB_<std::allocator<void> > FadeRGB;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::FadeRGB > FadeRGBPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::FadeRGB const> FadeRGBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator2> & rhs)
{
  return lhs.led_name == rhs.led_name &&
    lhs.color == rhs.color &&
    lhs.fade_duration == rhs.fade_duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0df8c8fbe7f1de5f2168d6117ffced08";
  }

  static const char* value(const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0df8c8fbe7f1de5fULL;
  static const uint64_t static_value2 = 0x2168d6117ffced08ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/FadeRGB";
  }

  static const char* value(const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Message to fade leds\n"
"string led_name\n"
"std_msgs/ColorRGBA color\n"
"duration fade_duration\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_name);
      stream.next(m.color);
      stream.next(m.fade_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FadeRGB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::FadeRGB_<ContainerAllocator>& v)
  {
    s << indent << "led_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.led_name);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "fade_duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.fade_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_FADERGB_H
