// Generated by gencpp from file naoqi_bridge_msgs/FollowPathFeedback.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_FOLLOWPATHFEEDBACK_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_FOLLOWPATHFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct FollowPathFeedback_
{
  typedef FollowPathFeedback_<ContainerAllocator> Type;

  FollowPathFeedback_()
    : index(0)  {
    }
  FollowPathFeedback_(const ContainerAllocator& _alloc)
    : index(0)  {
  (void)_alloc;
    }



   typedef uint32_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FollowPathFeedback_

typedef ::naoqi_bridge_msgs::FollowPathFeedback_<std::allocator<void> > FollowPathFeedback;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::FollowPathFeedback > FollowPathFeedbackPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::FollowPathFeedback const> FollowPathFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad7b979103dbd563a352ef5270716728";
  }

  static const char* value(const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad7b979103dbd563ULL;
  static const uint64_t static_value2 = 0xa352ef5270716728ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/FollowPathFeedback";
  }

  static const char* value(const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback: index of current subgoal in path\n"
"uint32 index\n"
"\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowPathFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::FollowPathFeedback_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_FOLLOWPATHFEEDBACK_H
