// Generated by gencpp from file naoqi_bridge_msgs/GetBodyROI.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETBODYROI_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETBODYROI_H

#include <ros/service_traits.h>


#include <naoqi_bridge_msgs/GetBodyROIRequest.h>
#include <naoqi_bridge_msgs/GetBodyROIResponse.h>


namespace naoqi_bridge_msgs
{

struct GetBodyROI
{

typedef GetBodyROIRequest Request;
typedef GetBodyROIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBodyROI
} // namespace naoqi_bridge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetBodyROI > {
  static const char* value()
  {
    return "ecc2963facbb989a955948135b6e21fd";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetBodyROI&) { return value(); }
};

template<>
struct DataType< ::naoqi_bridge_msgs::GetBodyROI > {
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetBodyROI";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetBodyROI&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetBodyROIRequest> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetBodyROI >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetBodyROIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetBodyROI >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetBodyROIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetBodyROIRequest> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetBodyROI >
template<>
struct DataType< ::naoqi_bridge_msgs::GetBodyROIRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetBodyROI >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetBodyROIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetBodyROIResponse> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetBodyROI >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetBodyROIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetBodyROI >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetBodyROIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetBodyROIResponse> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetBodyROI >
template<>
struct DataType< ::naoqi_bridge_msgs::GetBodyROIResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetBodyROI >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetBodyROIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETBODYROI_H
