// Generated by gencpp from file naoqi_bridge_msgs/GetFloatResponse.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETFLOATRESPONSE_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETFLOATRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct GetFloatResponse_
{
  typedef GetFloatResponse_<ContainerAllocator> Type;

  GetFloatResponse_()
    : data(0.0)
    , message()  {
    }
  GetFloatResponse_(const ContainerAllocator& _alloc)
    : data(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFloatResponse_

typedef ::naoqi_bridge_msgs::GetFloatResponse_<std::allocator<void> > GetFloatResponse;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFloatResponse > GetFloatResponsePtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFloatResponse const> GetFloatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cf398eaca21304d20b13c76cecbddea";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cf398eaca21304dULL;
  static const uint64_t static_value2 = 0x20b13c76cecbddeaULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetFloatResponse";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFloatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::GetFloatResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETFLOATRESPONSE_H
