// Generated by gencpp from file naoqi_bridge_msgs/GetFacesROIResponse.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETFACESROIRESPONSE_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETFACESROIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <naoqi_bridge_msgs/FaceROI.h>

namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct GetFacesROIResponse_
{
  typedef GetFacesROIResponse_<ContainerAllocator> Type;

  GetFacesROIResponse_()
    : faces()  {
    }
  GetFacesROIResponse_(const ContainerAllocator& _alloc)
    : faces(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::naoqi_bridge_msgs::FaceROI_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::naoqi_bridge_msgs::FaceROI_<ContainerAllocator> >::other >  _faces_type;
  _faces_type faces;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFacesROIResponse_

typedef ::naoqi_bridge_msgs::GetFacesROIResponse_<std::allocator<void> > GetFacesROIResponse;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFacesROIResponse > GetFacesROIResponsePtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetFacesROIResponse const> GetFacesROIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator2> & rhs)
{
  return lhs.faces == rhs.faces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7123975ed3d5d1cde8b35e6736592769";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7123975ed3d5d1cdULL;
  static const uint64_t static_value2 = 0xe8b35e6736592769ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetFacesROIResponse";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FaceROI[] faces\n"
"\n"
"\n"
"================================================================================\n"
"MSG: naoqi_bridge_msgs/FaceROI\n"
"float32 angle\n"
"float32 cx\n"
"float32 cy\n"
"float32 height\n"
"float32 width\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.faces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFacesROIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::GetFacesROIResponse_<ContainerAllocator>& v)
  {
    s << indent << "faces[]" << std::endl;
    for (size_t i = 0; i < v.faces.size(); ++i)
    {
      s << indent << "  faces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::naoqi_bridge_msgs::FaceROI_<ContainerAllocator> >::stream(s, indent + "    ", v.faces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETFACESROIRESPONSE_H
