// Generated by gencpp from file naoqi_bridge_msgs/GetInstalledBehaviorsRequest.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETINSTALLEDBEHAVIORSREQUEST_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETINSTALLEDBEHAVIORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct GetInstalledBehaviorsRequest_
{
  typedef GetInstalledBehaviorsRequest_<ContainerAllocator> Type;

  GetInstalledBehaviorsRequest_()
    {
    }
  GetInstalledBehaviorsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInstalledBehaviorsRequest_

typedef ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<std::allocator<void> > GetInstalledBehaviorsRequest;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest > GetInstalledBehaviorsRequestPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest const> GetInstalledBehaviorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetInstalledBehaviorsRequest";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# List installed behaviors on the robot\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInstalledBehaviorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETINSTALLEDBEHAVIORSREQUEST_H
