// Generated by gencpp from file naoqi_bridge_msgs/GetInstalledBehaviors.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETINSTALLEDBEHAVIORS_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETINSTALLEDBEHAVIORS_H

#include <ros/service_traits.h>


#include <naoqi_bridge_msgs/GetInstalledBehaviorsRequest.h>
#include <naoqi_bridge_msgs/GetInstalledBehaviorsResponse.h>


namespace naoqi_bridge_msgs
{

struct GetInstalledBehaviors
{

typedef GetInstalledBehaviorsRequest Request;
typedef GetInstalledBehaviorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInstalledBehaviors
} // namespace naoqi_bridge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviors > {
  static const char* value()
  {
    return "715783c8c6eb28fc2e1c05184add75ec";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviors&) { return value(); }
};

template<>
struct DataType< ::naoqi_bridge_msgs::GetInstalledBehaviors > {
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetInstalledBehaviors";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviors&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviors >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviors >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetInstalledBehaviors >
template<>
struct DataType< ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetInstalledBehaviors >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviorsResponse> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviors >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetInstalledBehaviors >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetInstalledBehaviorsResponse> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetInstalledBehaviors >
template<>
struct DataType< ::naoqi_bridge_msgs::GetInstalledBehaviorsResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetInstalledBehaviors >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetInstalledBehaviorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETINSTALLEDBEHAVIORS_H
