// Generated by gencpp from file naoqi_bridge_msgs/GetRobotInfo.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETROBOTINFO_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETROBOTINFO_H

#include <ros/service_traits.h>


#include <naoqi_bridge_msgs/GetRobotInfoRequest.h>
#include <naoqi_bridge_msgs/GetRobotInfoResponse.h>


namespace naoqi_bridge_msgs
{

struct GetRobotInfo
{

typedef GetRobotInfoRequest Request;
typedef GetRobotInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotInfo
} // namespace naoqi_bridge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetRobotInfo > {
  static const char* value()
  {
    return "6a705e4ea65692d6e21188b3537da43d";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetRobotInfo&) { return value(); }
};

template<>
struct DataType< ::naoqi_bridge_msgs::GetRobotInfo > {
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetRobotInfo";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetRobotInfo&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetRobotInfoRequest> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetRobotInfo >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetRobotInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetRobotInfo >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetRobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetRobotInfoRequest> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetRobotInfo >
template<>
struct DataType< ::naoqi_bridge_msgs::GetRobotInfoRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetRobotInfo >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetRobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetRobotInfoResponse> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetRobotInfo >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetRobotInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetRobotInfo >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetRobotInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetRobotInfoResponse> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetRobotInfo >
template<>
struct DataType< ::naoqi_bridge_msgs::GetRobotInfoResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetRobotInfo >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetRobotInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETROBOTINFO_H
