// Generated by gencpp from file naoqi_bridge_msgs/GetTruepose.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_GETTRUEPOSE_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_GETTRUEPOSE_H

#include <ros/service_traits.h>


#include <naoqi_bridge_msgs/GetTrueposeRequest.h>
#include <naoqi_bridge_msgs/GetTrueposeResponse.h>


namespace naoqi_bridge_msgs
{

struct GetTruepose
{

typedef GetTrueposeRequest Request;
typedef GetTrueposeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTruepose
} // namespace naoqi_bridge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetTruepose > {
  static const char* value()
  {
    return "4f3e0bbe7a24e1f929488cd1970222d3";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetTruepose&) { return value(); }
};

template<>
struct DataType< ::naoqi_bridge_msgs::GetTruepose > {
  static const char* value()
  {
    return "naoqi_bridge_msgs/GetTruepose";
  }

  static const char* value(const ::naoqi_bridge_msgs::GetTruepose&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetTrueposeRequest> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetTruepose >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetTrueposeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetTruepose >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetTrueposeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetTrueposeRequest> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetTruepose >
template<>
struct DataType< ::naoqi_bridge_msgs::GetTrueposeRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetTruepose >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetTrueposeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetTrueposeResponse> should match
// service_traits::MD5Sum< ::naoqi_bridge_msgs::GetTruepose >
template<>
struct MD5Sum< ::naoqi_bridge_msgs::GetTrueposeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_bridge_msgs::GetTruepose >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetTrueposeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_bridge_msgs::GetTrueposeResponse> should match
// service_traits::DataType< ::naoqi_bridge_msgs::GetTruepose >
template<>
struct DataType< ::naoqi_bridge_msgs::GetTrueposeResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_bridge_msgs::GetTruepose >::value();
  }
  static const char* value(const ::naoqi_bridge_msgs::GetTrueposeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_GETTRUEPOSE_H
