// Generated by gencpp from file naoqi_bridge_msgs/MemoryPairString.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_MEMORYPAIRSTRING_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_MEMORYPAIRSTRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct MemoryPairString_
{
  typedef MemoryPairString_<ContainerAllocator> Type;

  MemoryPairString_()
    : memoryKey()
    , data()  {
    }
  MemoryPairString_(const ContainerAllocator& _alloc)
    : memoryKey(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _memoryKey_type;
  _memoryKey_type memoryKey;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> const> ConstPtr;

}; // struct MemoryPairString_

typedef ::naoqi_bridge_msgs::MemoryPairString_<std::allocator<void> > MemoryPairString;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::MemoryPairString > MemoryPairStringPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::MemoryPairString const> MemoryPairStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator2> & rhs)
{
  return lhs.memoryKey == rhs.memoryKey &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6046f2881035869712dcfeda0628929";
  }

  static const char* value(const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6046f2881035869ULL;
  static const uint64_t static_value2 = 0x712dcfeda0628929ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/MemoryPairString";
  }

  static const char* value(const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string memoryKey\n"
"string data\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.memoryKey);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MemoryPairString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::MemoryPairString_<ContainerAllocator>& v)
  {
    s << indent << "memoryKey: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.memoryKey);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_MEMORYPAIRSTRING_H
