// Generated by gencpp from file naoqi_bridge_msgs/SetSpeechVocabularyGoal.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_SETSPEECHVOCABULARYGOAL_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_SETSPEECHVOCABULARYGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct SetSpeechVocabularyGoal_
{
  typedef SetSpeechVocabularyGoal_<ContainerAllocator> Type;

  SetSpeechVocabularyGoal_()
    : words()  {
    }
  SetSpeechVocabularyGoal_(const ContainerAllocator& _alloc)
    : words(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _words_type;
  _words_type words;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpeechVocabularyGoal_

typedef ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<std::allocator<void> > SetSpeechVocabularyGoal;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal > SetSpeechVocabularyGoalPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal const> SetSpeechVocabularyGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator2> & rhs)
{
  return lhs.words == rhs.words;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bd0e7dd008cf8f52a5113ba090403b7";
  }

  static const char* value(const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bd0e7dd008cf8f5ULL;
  static const uint64_t static_value2 = 0x2a5113ba090403b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/SetSpeechVocabularyGoal";
  }

  static const char* value(const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal: The new vocabulary to be set in the speech recognition module\n"
"# Result: True if the vocabulary was set\n"
"# Feedback: None\n"
"\n"
"string[] words\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.words);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpeechVocabularyGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::SetSpeechVocabularyGoal_<ContainerAllocator>& v)
  {
    s << indent << "words[]" << std::endl;
    for (size_t i = 0; i < v.words.size(); ++i)
    {
      s << indent << "  words[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.words[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_SETSPEECHVOCABULARYGOAL_H
