// Generated by gencpp from file naoqi_bridge_msgs/SpeechWithFeedbackGoal.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_SPEECHWITHFEEDBACKGOAL_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_SPEECHWITHFEEDBACKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct SpeechWithFeedbackGoal_
{
  typedef SpeechWithFeedbackGoal_<ContainerAllocator> Type;

  SpeechWithFeedbackGoal_()
    : say()  {
    }
  SpeechWithFeedbackGoal_(const ContainerAllocator& _alloc)
    : say(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _say_type;
  _say_type say;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechWithFeedbackGoal_

typedef ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<std::allocator<void> > SpeechWithFeedbackGoal;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal > SpeechWithFeedbackGoalPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal const> SpeechWithFeedbackGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator2> & rhs)
{
  return lhs.say == rhs.say;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "331898fd34308d7c3706d43ca7f6e377";
  }

  static const char* value(const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x331898fd34308d7cULL;
  static const uint64_t static_value2 = 0x3706d43ca7f6e377ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/SpeechWithFeedbackGoal";
  }

  static const char* value(const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Purpose : To have feedback on when the speech was started and when \n"
"# NAO stopped talking\n"
"# Goal: The sentence for NAO to say \n"
"# Result: NAO has finished speaking\n"
"# Feedback: When NAO starts speaking\n"
"\n"
"string say\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.say);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechWithFeedbackGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::SpeechWithFeedbackGoal_<ContainerAllocator>& v)
  {
    s << indent << "say: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.say);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_SPEECHWITHFEEDBACKGOAL_H
