// Generated by gencpp from file naoqi_bridge_msgs/StatusChangeStamped.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_STATUSCHANGESTAMPED_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_STATUSCHANGESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <std_msgs/String.h>

namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct StatusChangeStamped_
{
  typedef StatusChangeStamped_<ContainerAllocator> Type;

  StatusChangeStamped_()
    : header()
    , recharge_type(0)
    , old_status()
    , new_status()  {
    }
  StatusChangeStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , recharge_type(0)
    , old_status(_alloc)
    , new_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _recharge_type_type;
  _recharge_type_type recharge_type;

   typedef  ::std_msgs::String_<ContainerAllocator>  _old_status_type;
  _old_status_type old_status;

   typedef  ::std_msgs::String_<ContainerAllocator>  _new_status_type;
  _new_status_type new_status;





  typedef boost::shared_ptr< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> const> ConstPtr;

}; // struct StatusChangeStamped_

typedef ::naoqi_bridge_msgs::StatusChangeStamped_<std::allocator<void> > StatusChangeStamped;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::StatusChangeStamped > StatusChangeStampedPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::StatusChangeStamped const> StatusChangeStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.recharge_type == rhs.recharge_type &&
    lhs.old_status == rhs.old_status &&
    lhs.new_status == rhs.new_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator1> & lhs, const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "631ab2246eca82d839e3a99b76567775";
  }

  static const char* value(const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x631ab2246eca82d8ULL;
  static const uint64_t static_value2 = 0x39e3a99b76567775ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/StatusChangeStamped";
  }

  static const char* value(const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16 recharge_type\n"
"std_msgs/String old_status\n"
"std_msgs/String new_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.recharge_type);
      stream.next(m.old_status);
      stream.next(m.new_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusChangeStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::StatusChangeStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "recharge_type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.recharge_type);
    s << indent << "old_status: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.old_status);
    s << indent << "new_status: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.new_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_STATUSCHANGESTAMPED_H
