// Auto-generated. Do not edit!

// (in-package naoqi_bridge_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let JointAnglesWithSpeed = require('./JointAnglesWithSpeed.js');

//-----------------------------------------------------------

class JointAnglesWithSpeedGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.joint_angles = null;
    }
    else {
      if (initObj.hasOwnProperty('joint_angles')) {
        this.joint_angles = initObj.joint_angles
      }
      else {
        this.joint_angles = new JointAnglesWithSpeed();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type JointAnglesWithSpeedGoal
    // Serialize message field [joint_angles]
    bufferOffset = JointAnglesWithSpeed.serialize(obj.joint_angles, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type JointAnglesWithSpeedGoal
    let len;
    let data = new JointAnglesWithSpeedGoal(null);
    // Deserialize message field [joint_angles]
    data.joint_angles = JointAnglesWithSpeed.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += JointAnglesWithSpeed.getMessageSize(object.joint_angles);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'naoqi_bridge_msgs/JointAnglesWithSpeedGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd19a898a40aae87b37b0f91c9e90f46c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal: a registered body pose name
    naoqi_bridge_msgs/JointAnglesWithSpeed joint_angles
    
    ================================================================================
    MSG: naoqi_bridge_msgs/JointAnglesWithSpeed
    Header header
    
    # A list of joint names, corresponding to their names in the Nao docs.
    # This must either have the same length as joint_angles or 
    # length 1 if it's a keyword such as 'Body' (for all angles)
    string[] joint_names
    float32[] joint_angles
    
    # fraction of max joint velocity [0:1]
    float32 speed
    
    # Absolute angle (=0, default) or relative change
    uint8 relative
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new JointAnglesWithSpeedGoal(null);
    if (msg.joint_angles !== undefined) {
      resolved.joint_angles = JointAnglesWithSpeed.Resolve(msg.joint_angles)
    }
    else {
      resolved.joint_angles = new JointAnglesWithSpeed()
    }

    return resolved;
    }
};

module.exports = JointAnglesWithSpeedGoal;
