// Generated by gencpp from file detect_srv/Detect.msg
// DO NOT EDIT!


#ifndef DETECT_SRV_MESSAGE_DETECT_H
#define DETECT_SRV_MESSAGE_DETECT_H

#include <ros/service_traits.h>


#include <detect_srv/DetectRequest.h>
#include <detect_srv/DetectResponse.h>


namespace detect_srv
{

struct Detect
{

typedef DetectRequest Request;
typedef DetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detect
} // namespace detect_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detect_srv::Detect > {
  static const char* value()
  {
    return "cbdd439cb37e9b917711bccd925048b5";
  }

  static const char* value(const ::detect_srv::Detect&) { return value(); }
};

template<>
struct DataType< ::detect_srv::Detect > {
  static const char* value()
  {
    return "detect_srv/Detect";
  }

  static const char* value(const ::detect_srv::Detect&) { return value(); }
};


// service_traits::MD5Sum< ::detect_srv::DetectRequest> should match
// service_traits::MD5Sum< ::detect_srv::Detect >
template<>
struct MD5Sum< ::detect_srv::DetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detect_srv::Detect >::value();
  }
  static const char* value(const ::detect_srv::DetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_srv::DetectRequest> should match
// service_traits::DataType< ::detect_srv::Detect >
template<>
struct DataType< ::detect_srv::DetectRequest>
{
  static const char* value()
  {
    return DataType< ::detect_srv::Detect >::value();
  }
  static const char* value(const ::detect_srv::DetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detect_srv::DetectResponse> should match
// service_traits::MD5Sum< ::detect_srv::Detect >
template<>
struct MD5Sum< ::detect_srv::DetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detect_srv::Detect >::value();
  }
  static const char* value(const ::detect_srv::DetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_srv::DetectResponse> should match
// service_traits::DataType< ::detect_srv::Detect >
template<>
struct DataType< ::detect_srv::DetectResponse>
{
  static const char* value()
  {
    return DataType< ::detect_srv::Detect >::value();
  }
  static const char* value(const ::detect_srv::DetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECT_SRV_MESSAGE_DETECT_H
