; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude BodyPoseGoal.msg.html

(cl:defclass <BodyPoseGoal> (roslisp-msg-protocol:ros-message)
  ((pose_name
    :reader pose_name
    :initarg :pose_name
    :type cl:string
    :initform ""))
)

(cl:defclass BodyPoseGoal (<BodyPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BodyPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BodyPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<BodyPoseGoal> is deprecated: use naoqi_bridge_msgs-msg:BodyPoseGoal instead.")))

(cl:ensure-generic-function 'pose_name-val :lambda-list '(m))
(cl:defmethod pose_name-val ((m <BodyPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader naoqi_bridge_msgs-msg:pose_name-val is deprecated.  Use naoqi_bridge_msgs-msg:pose_name instead.")
  (pose_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BodyPoseGoal>) ostream)
  "Serializes a message object of type '<BodyPoseGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'pose_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'pose_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BodyPoseGoal>) istream)
  "Deserializes a message object of type '<BodyPoseGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'pose_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'pose_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BodyPoseGoal>)))
  "Returns string type for a message object of type '<BodyPoseGoal>"
  "naoqi_bridge_msgs/BodyPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BodyPoseGoal)))
  "Returns string type for a message object of type 'BodyPoseGoal"
  "naoqi_bridge_msgs/BodyPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BodyPoseGoal>)))
  "Returns md5sum for a message object of type '<BodyPoseGoal>"
  "e6184073e8e665fb2bf0be194fc36541")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BodyPoseGoal)))
  "Returns md5sum for a message object of type 'BodyPoseGoal"
  "e6184073e8e665fb2bf0be194fc36541")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BodyPoseGoal>)))
  "Returns full string definition for message of type '<BodyPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a registered body pose name~%string pose_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BodyPoseGoal)))
  "Returns full string definition for message of type 'BodyPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a registered body pose name~%string pose_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BodyPoseGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'pose_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BodyPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BodyPoseGoal
    (cl:cons ':pose_name (pose_name msg))
))
