; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude BodyPoseWithSpeedGoal.msg.html

(cl:defclass <BodyPoseWithSpeedGoal> (roslisp-msg-protocol:ros-message)
  ((posture_name
    :reader posture_name
    :initarg :posture_name
    :type cl:string
    :initform "")
   (speed
    :reader speed
    :initarg :speed
    :type cl:float
    :initform 0.0))
)

(cl:defclass BodyPoseWithSpeedGoal (<BodyPoseWithSpeedGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BodyPoseWithSpeedGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BodyPoseWithSpeedGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<BodyPoseWithSpeedGoal> is deprecated: use naoqi_bridge_msgs-msg:BodyPoseWithSpeedGoal instead.")))

(cl:ensure-generic-function 'posture_name-val :lambda-list '(m))
(cl:defmethod posture_name-val ((m <BodyPoseWithSpeedGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader naoqi_bridge_msgs-msg:posture_name-val is deprecated.  Use naoqi_bridge_msgs-msg:posture_name instead.")
  (posture_name m))

(cl:ensure-generic-function 'speed-val :lambda-list '(m))
(cl:defmethod speed-val ((m <BodyPoseWithSpeedGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader naoqi_bridge_msgs-msg:speed-val is deprecated.  Use naoqi_bridge_msgs-msg:speed instead.")
  (speed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BodyPoseWithSpeedGoal>) ostream)
  "Serializes a message object of type '<BodyPoseWithSpeedGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'posture_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'posture_name))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'speed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BodyPoseWithSpeedGoal>) istream)
  "Deserializes a message object of type '<BodyPoseWithSpeedGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'posture_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'posture_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'speed) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BodyPoseWithSpeedGoal>)))
  "Returns string type for a message object of type '<BodyPoseWithSpeedGoal>"
  "naoqi_bridge_msgs/BodyPoseWithSpeedGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BodyPoseWithSpeedGoal)))
  "Returns string type for a message object of type 'BodyPoseWithSpeedGoal"
  "naoqi_bridge_msgs/BodyPoseWithSpeedGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BodyPoseWithSpeedGoal>)))
  "Returns md5sum for a message object of type '<BodyPoseWithSpeedGoal>"
  "6c5f7bd37d2a5befe00383fa440a8f6e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BodyPoseWithSpeedGoal)))
  "Returns md5sum for a message object of type 'BodyPoseWithSpeedGoal"
  "6c5f7bd37d2a5befe00383fa440a8f6e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BodyPoseWithSpeedGoal>)))
  "Returns full string definition for message of type '<BodyPoseWithSpeedGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a predefined body pose name :~%# Crouch, LyingBack, LyingBelly, Sit, SitRelax, Stand, StandInit, StandZero~%~%string posture_name~%float32 speed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BodyPoseWithSpeedGoal)))
  "Returns full string definition for message of type 'BodyPoseWithSpeedGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a predefined body pose name :~%# Crouch, LyingBack, LyingBelly, Sit, SitRelax, Stand, StandInit, StandZero~%~%string posture_name~%float32 speed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BodyPoseWithSpeedGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'posture_name))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BodyPoseWithSpeedGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BodyPoseWithSpeedGoal
    (cl:cons ':posture_name (posture_name msg))
    (cl:cons ':speed (speed msg))
))
