; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude BodyPoseWithSpeedFeedback.msg.html

(cl:defclass <BodyPoseWithSpeedFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass BodyPoseWithSpeedFeedback (<BodyPoseWithSpeedFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BodyPoseWithSpeedFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BodyPoseWithSpeedFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<BodyPoseWithSpeedFeedback> is deprecated: use naoqi_bridge_msgs-msg:BodyPoseWithSpeedFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BodyPoseWithSpeedFeedback>) ostream)
  "Serializes a message object of type '<BodyPoseWithSpeedFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BodyPoseWithSpeedFeedback>) istream)
  "Deserializes a message object of type '<BodyPoseWithSpeedFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BodyPoseWithSpeedFeedback>)))
  "Returns string type for a message object of type '<BodyPoseWithSpeedFeedback>"
  "naoqi_bridge_msgs/BodyPoseWithSpeedFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BodyPoseWithSpeedFeedback)))
  "Returns string type for a message object of type 'BodyPoseWithSpeedFeedback"
  "naoqi_bridge_msgs/BodyPoseWithSpeedFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BodyPoseWithSpeedFeedback>)))
  "Returns md5sum for a message object of type '<BodyPoseWithSpeedFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BodyPoseWithSpeedFeedback)))
  "Returns md5sum for a message object of type 'BodyPoseWithSpeedFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BodyPoseWithSpeedFeedback>)))
  "Returns full string definition for message of type '<BodyPoseWithSpeedFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BodyPoseWithSpeedFeedback)))
  "Returns full string definition for message of type 'BodyPoseWithSpeedFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BodyPoseWithSpeedFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BodyPoseWithSpeedFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'BodyPoseWithSpeedFeedback
))
