; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude FollowPathFeedback.msg.html

(cl:defclass <FollowPathFeedback> (roslisp-msg-protocol:ros-message)
  ((index
    :reader index
    :initarg :index
    :type cl:integer
    :initform 0))
)

(cl:defclass FollowPathFeedback (<FollowPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<FollowPathFeedback> is deprecated: use naoqi_bridge_msgs-msg:FollowPathFeedback instead.")))

(cl:ensure-generic-function 'index-val :lambda-list '(m))
(cl:defmethod index-val ((m <FollowPathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader naoqi_bridge_msgs-msg:index-val is deprecated.  Use naoqi_bridge_msgs-msg:index instead.")
  (index m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathFeedback>) ostream)
  "Serializes a message object of type '<FollowPathFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'index)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathFeedback>) istream)
  "Deserializes a message object of type '<FollowPathFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'index)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathFeedback>)))
  "Returns string type for a message object of type '<FollowPathFeedback>"
  "naoqi_bridge_msgs/FollowPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathFeedback)))
  "Returns string type for a message object of type 'FollowPathFeedback"
  "naoqi_bridge_msgs/FollowPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathFeedback>)))
  "Returns md5sum for a message object of type '<FollowPathFeedback>"
  "ad7b979103dbd563a352ef5270716728")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathFeedback)))
  "Returns md5sum for a message object of type 'FollowPathFeedback"
  "ad7b979103dbd563a352ef5270716728")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathFeedback>)))
  "Returns full string definition for message of type '<FollowPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback: index of current subgoal in path~%uint32 index~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathFeedback)))
  "Returns full string definition for message of type 'FollowPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback: index of current subgoal in path~%uint32 index~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathFeedback
    (cl:cons ':index (index msg))
))
