; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude JointAnglesWithSpeedGoal.msg.html

(cl:defclass <JointAnglesWithSpeedGoal> (roslisp-msg-protocol:ros-message)
  ((joint_angles
    :reader joint_angles
    :initarg :joint_angles
    :type naoqi_bridge_msgs-msg:JointAnglesWithSpeed
    :initform (cl:make-instance 'naoqi_bridge_msgs-msg:JointAnglesWithSpeed)))
)

(cl:defclass JointAnglesWithSpeedGoal (<JointAnglesWithSpeedGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointAnglesWithSpeedGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointAnglesWithSpeedGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<JointAnglesWithSpeedGoal> is deprecated: use naoqi_bridge_msgs-msg:JointAnglesWithSpeedGoal instead.")))

(cl:ensure-generic-function 'joint_angles-val :lambda-list '(m))
(cl:defmethod joint_angles-val ((m <JointAnglesWithSpeedGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader naoqi_bridge_msgs-msg:joint_angles-val is deprecated.  Use naoqi_bridge_msgs-msg:joint_angles instead.")
  (joint_angles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointAnglesWithSpeedGoal>) ostream)
  "Serializes a message object of type '<JointAnglesWithSpeedGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'joint_angles) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointAnglesWithSpeedGoal>) istream)
  "Deserializes a message object of type '<JointAnglesWithSpeedGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'joint_angles) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointAnglesWithSpeedGoal>)))
  "Returns string type for a message object of type '<JointAnglesWithSpeedGoal>"
  "naoqi_bridge_msgs/JointAnglesWithSpeedGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointAnglesWithSpeedGoal)))
  "Returns string type for a message object of type 'JointAnglesWithSpeedGoal"
  "naoqi_bridge_msgs/JointAnglesWithSpeedGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointAnglesWithSpeedGoal>)))
  "Returns md5sum for a message object of type '<JointAnglesWithSpeedGoal>"
  "d19a898a40aae87b37b0f91c9e90f46c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointAnglesWithSpeedGoal)))
  "Returns md5sum for a message object of type 'JointAnglesWithSpeedGoal"
  "d19a898a40aae87b37b0f91c9e90f46c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointAnglesWithSpeedGoal>)))
  "Returns full string definition for message of type '<JointAnglesWithSpeedGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a registered body pose name~%naoqi_bridge_msgs/JointAnglesWithSpeed joint_angles~%~%================================================================================~%MSG: naoqi_bridge_msgs/JointAnglesWithSpeed~%Header header~%~%# A list of joint names, corresponding to their names in the Nao docs.~%# This must either have the same length as joint_angles or ~%# length 1 if it's a keyword such as 'Body' (for all angles)~%string[] joint_names~%float32[] joint_angles~%~%# fraction of max joint velocity [0:1]~%float32 speed~%~%# Absolute angle (=0, default) or relative change~%uint8 relative~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointAnglesWithSpeedGoal)))
  "Returns full string definition for message of type 'JointAnglesWithSpeedGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a registered body pose name~%naoqi_bridge_msgs/JointAnglesWithSpeed joint_angles~%~%================================================================================~%MSG: naoqi_bridge_msgs/JointAnglesWithSpeed~%Header header~%~%# A list of joint names, corresponding to their names in the Nao docs.~%# This must either have the same length as joint_angles or ~%# length 1 if it's a keyword such as 'Body' (for all angles)~%string[] joint_names~%float32[] joint_angles~%~%# fraction of max joint velocity [0:1]~%float32 speed~%~%# Absolute angle (=0, default) or relative change~%uint8 relative~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointAnglesWithSpeedGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'joint_angles))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointAnglesWithSpeedGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JointAnglesWithSpeedGoal
    (cl:cons ':joint_angles (joint_angles msg))
))
