; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude SetSpeechVocabularyFeedback.msg.html

(cl:defclass <SetSpeechVocabularyFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SetSpeechVocabularyFeedback (<SetSpeechVocabularyFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetSpeechVocabularyFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetSpeechVocabularyFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<SetSpeechVocabularyFeedback> is deprecated: use naoqi_bridge_msgs-msg:SetSpeechVocabularyFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetSpeechVocabularyFeedback>) ostream)
  "Serializes a message object of type '<SetSpeechVocabularyFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetSpeechVocabularyFeedback>) istream)
  "Deserializes a message object of type '<SetSpeechVocabularyFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetSpeechVocabularyFeedback>)))
  "Returns string type for a message object of type '<SetSpeechVocabularyFeedback>"
  "naoqi_bridge_msgs/SetSpeechVocabularyFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetSpeechVocabularyFeedback)))
  "Returns string type for a message object of type 'SetSpeechVocabularyFeedback"
  "naoqi_bridge_msgs/SetSpeechVocabularyFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetSpeechVocabularyFeedback>)))
  "Returns md5sum for a message object of type '<SetSpeechVocabularyFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetSpeechVocabularyFeedback)))
  "Returns md5sum for a message object of type 'SetSpeechVocabularyFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetSpeechVocabularyFeedback>)))
  "Returns full string definition for message of type '<SetSpeechVocabularyFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetSpeechVocabularyFeedback)))
  "Returns full string definition for message of type 'SetSpeechVocabularyFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetSpeechVocabularyFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetSpeechVocabularyFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetSpeechVocabularyFeedback
))
