; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude SpeechWithFeedbackGoal.msg.html

(cl:defclass <SpeechWithFeedbackGoal> (roslisp-msg-protocol:ros-message)
  ((say
    :reader say
    :initarg :say
    :type cl:string
    :initform ""))
)

(cl:defclass SpeechWithFeedbackGoal (<SpeechWithFeedbackGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SpeechWithFeedbackGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SpeechWithFeedbackGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<SpeechWithFeedbackGoal> is deprecated: use naoqi_bridge_msgs-msg:SpeechWithFeedbackGoal instead.")))

(cl:ensure-generic-function 'say-val :lambda-list '(m))
(cl:defmethod say-val ((m <SpeechWithFeedbackGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader naoqi_bridge_msgs-msg:say-val is deprecated.  Use naoqi_bridge_msgs-msg:say instead.")
  (say m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SpeechWithFeedbackGoal>) ostream)
  "Serializes a message object of type '<SpeechWithFeedbackGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'say))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'say))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SpeechWithFeedbackGoal>) istream)
  "Deserializes a message object of type '<SpeechWithFeedbackGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'say) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'say) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SpeechWithFeedbackGoal>)))
  "Returns string type for a message object of type '<SpeechWithFeedbackGoal>"
  "naoqi_bridge_msgs/SpeechWithFeedbackGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SpeechWithFeedbackGoal)))
  "Returns string type for a message object of type 'SpeechWithFeedbackGoal"
  "naoqi_bridge_msgs/SpeechWithFeedbackGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SpeechWithFeedbackGoal>)))
  "Returns md5sum for a message object of type '<SpeechWithFeedbackGoal>"
  "331898fd34308d7c3706d43ca7f6e377")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SpeechWithFeedbackGoal)))
  "Returns md5sum for a message object of type 'SpeechWithFeedbackGoal"
  "331898fd34308d7c3706d43ca7f6e377")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SpeechWithFeedbackGoal>)))
  "Returns full string definition for message of type '<SpeechWithFeedbackGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Purpose : To have feedback on when the speech was started and when ~%# NAO stopped talking~%# Goal: The sentence for NAO to say ~%# Result: NAO has finished speaking~%# Feedback: When NAO starts speaking~%~%string say~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SpeechWithFeedbackGoal)))
  "Returns full string definition for message of type 'SpeechWithFeedbackGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Purpose : To have feedback on when the speech was started and when ~%# NAO stopped talking~%# Goal: The sentence for NAO to say ~%# Result: NAO has finished speaking~%# Feedback: When NAO starts speaking~%~%string say~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SpeechWithFeedbackGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'say))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SpeechWithFeedbackGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SpeechWithFeedbackGoal
    (cl:cons ':say (say msg))
))
