; Auto-generated. Do not edit!


(cl:in-package naoqi_bridge_msgs-msg)


;//! \htmlinclude SpeechWithFeedbackResult.msg.html

(cl:defclass <SpeechWithFeedbackResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SpeechWithFeedbackResult (<SpeechWithFeedbackResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SpeechWithFeedbackResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SpeechWithFeedbackResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name naoqi_bridge_msgs-msg:<SpeechWithFeedbackResult> is deprecated: use naoqi_bridge_msgs-msg:SpeechWithFeedbackResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SpeechWithFeedbackResult>) ostream)
  "Serializes a message object of type '<SpeechWithFeedbackResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SpeechWithFeedbackResult>) istream)
  "Deserializes a message object of type '<SpeechWithFeedbackResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SpeechWithFeedbackResult>)))
  "Returns string type for a message object of type '<SpeechWithFeedbackResult>"
  "naoqi_bridge_msgs/SpeechWithFeedbackResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SpeechWithFeedbackResult)))
  "Returns string type for a message object of type 'SpeechWithFeedbackResult"
  "naoqi_bridge_msgs/SpeechWithFeedbackResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SpeechWithFeedbackResult>)))
  "Returns md5sum for a message object of type '<SpeechWithFeedbackResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SpeechWithFeedbackResult)))
  "Returns md5sum for a message object of type 'SpeechWithFeedbackResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SpeechWithFeedbackResult>)))
  "Returns full string definition for message of type '<SpeechWithFeedbackResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Empty result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SpeechWithFeedbackResult)))
  "Returns full string definition for message of type 'SpeechWithFeedbackResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Empty result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SpeechWithFeedbackResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SpeechWithFeedbackResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SpeechWithFeedbackResult
))
