// Generated by gencpp from file take_pic_srv/TakePic.msg
// DO NOT EDIT!


#ifndef TAKE_PIC_SRV_MESSAGE_TAKEPIC_H
#define TAKE_PIC_SRV_MESSAGE_TAKEPIC_H

#include <ros/service_traits.h>


#include <take_pic_srv/TakePicRequest.h>
#include <take_pic_srv/TakePicResponse.h>


namespace take_pic_srv
{

struct TakePic
{

typedef TakePicRequest Request;
typedef TakePicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakePic
} // namespace take_pic_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::take_pic_srv::TakePic > {
  static const char* value()
  {
    return "b13d2865c5af2a64e6e30ab1b56e1dd5";
  }

  static const char* value(const ::take_pic_srv::TakePic&) { return value(); }
};

template<>
struct DataType< ::take_pic_srv::TakePic > {
  static const char* value()
  {
    return "take_pic_srv/TakePic";
  }

  static const char* value(const ::take_pic_srv::TakePic&) { return value(); }
};


// service_traits::MD5Sum< ::take_pic_srv::TakePicRequest> should match
// service_traits::MD5Sum< ::take_pic_srv::TakePic >
template<>
struct MD5Sum< ::take_pic_srv::TakePicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::take_pic_srv::TakePic >::value();
  }
  static const char* value(const ::take_pic_srv::TakePicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::take_pic_srv::TakePicRequest> should match
// service_traits::DataType< ::take_pic_srv::TakePic >
template<>
struct DataType< ::take_pic_srv::TakePicRequest>
{
  static const char* value()
  {
    return DataType< ::take_pic_srv::TakePic >::value();
  }
  static const char* value(const ::take_pic_srv::TakePicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::take_pic_srv::TakePicResponse> should match
// service_traits::MD5Sum< ::take_pic_srv::TakePic >
template<>
struct MD5Sum< ::take_pic_srv::TakePicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::take_pic_srv::TakePic >::value();
  }
  static const char* value(const ::take_pic_srv::TakePicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::take_pic_srv::TakePicResponse> should match
// service_traits::DataType< ::take_pic_srv::TakePic >
template<>
struct DataType< ::take_pic_srv::TakePicResponse>
{
  static const char* value()
  {
    return DataType< ::take_pic_srv::TakePic >::value();
  }
  static const char* value(const ::take_pic_srv::TakePicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAKE_PIC_SRV_MESSAGE_TAKEPIC_H
